title: "Sergio Transcriptions. From images to research data"
description: > 
  This project offers a workflow to process documents from Sergio Mosquera's transcriptions of Libro venta esclavo (1810) fom Notaria Primera de Quibdó.

  In this project, we will:
  - Process the existing doc-level metadata file
  - Read a folder of image files ([JPG](https://app.box.com/folder/235653219613))
  - Split the images into single-page images for processing. Note that many documents should not be split.
  - Create a Hugging Face Dataset
  - Transcribe the images using the Qwen model in Lightning.ai
  - Process the transcriptions to extract structured data
  - Publish the project in a static site (TODO txt and PDF)
  - Remove black and purple background from images

vars:
  name: "Sergio Notebooks"
  language: "es"
  text_direction: 'horizontal-lr' #['horizontal-lr', 'horizontal-rl', 'vertical-lr', 'vertical-rl']
  version: "0.0.0"
  image_folder: "assets/JPG_TESTBED" 
  metadata_file: "'assets/Base de datos Cuadernos Sergio_Notaría Primera de Quibdó (1808-1825).xlsx'"
  split_image_folder: "assets/splits"
  cropped_image_folder: "assets/cropped"
  rotated_image_folder: "assets/rotated"
  background_removed_image_folder: "assets/background_removed"
  markdown_folder: "data"
  nlp_model: "es_dep_news_trf"
  model: "Qwen/Qwen2-VL-7B-Instruct"
  code_model: "Qwen/Qwen2.5-Coder-7B-Instruct"
  dataset_name: "fmb-quibdo/sergio-notebooks"
  adjusted_image_folder: "assets/adjusted"

directories: ["assets", "configs", "scripts","_site","_templates","prompts", "pipelines", "packages"]

workflows:
  all:
    - metadata
    - crop
    - split
    - rotate
    - dataset
    - transcribe
    - process
    - publish
  

commands:
  - name: metadata
    help: "Read existing metadata file save as metadata.json"
    script:
      - "python scripts/metadata.py ${vars.metadata_file} metadata.json"
    outputs:
      - metadata.json

  - name: crop
    help: "Crop the images to remove unnecessary borders."
    script:
      - "python scripts/crop.py ${vars.image_folder} ${vars.cropped_image_folder}"
    outputs:
      - ${vars.cropped_image_folder}

  - name: split
    help: "Split the images into single-page images for processing. Remove ruler from image"
    script:
      - "python scripts/split.py ${vars.cropped_image_folder} ${vars.split_image_folder}"
    outputs:
      - ${vars.split_image_folder}

  - name: rotate
    help: "Rotate the split images to straighten text."
    script:
      - "python scripts/rotate.py ${vars.split_image_folder} ${vars.rotated_image_folder}"
    outputs:
      - ${vars.rotated_image_folder}
 
  - name: remove_background
    help: "Remove black and purple background from images."
    script:
      - "python scripts/remove_background.py ${vars.rotated_image_folder} ${vars.background_removed_image_folder}"
    outputs:
      - ${vars.background_removed_image_folder}

  - name: adjust_image
    help: "Adjust contrast, exposure, and histogram of images to enhance text visibility."
    script:
      - "python scripts/adjust_image.py ${vars.background_removed_image_folder} ${vars.adjusted_image_folder}"
    outputs:
      - ${vars.adjusted_image_folder}

  - name: dataset
    help: "Create a Hugging Face Dataset"
    script:
      - "python scripts/dataset.py ${vars.split_image_folder} ${vars.dataset_name}"

  # To run transcription on a local folder of images
  - name: transcribe
    help: "Transcribe the images"
    script:
      - "python scripts/transcribe.py ${vars.split_image_folder} ${vars.model}"
    outputs:
      - assets/
  
  # - name: transcribe
  #   help: "Transcribe images from HF Dataset"
  #   script:
  #     - "python scripts/hf_transcribe.py ${vars.dataset_name} ${vars.model}"
  #   outputs:
  #     - assets/

  - name: process
    help: "Process the transcriptions"
    script:
      - "python scripts/process.py data/ ${vars.nlp_model} data/data.jsonl"
    outputs:
      - assets/
  
  - name: publish
    help: "Publish the project"
    script:
      - "python scripts/publish.py ${vars.split_image_folder} ${vars.split_image_folder}/data.jsonl _site "
    outputs:
      - _site/

  - name: weasel
    help: "Force the weasel command to run again"
    script:
      - "python scripts/weasel.py --force"
    outputs:
      - weasel_output/
